- name:                      "Render {{ __connections_env_install_env }}"
  template:
    src:                     "helmvars/connections-env.yml.j2"
    dest:                    "{{ __connections_env_install_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "cat {{ __ansible_cache_charts }}/helm_repo_version_list | grep connections-env | cut -d ':' -f2"
  register:                  connections_env_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found connections-env chart version
  debug:
    msg:                     "{{ connections_env_chart_version.stdout }}"

- name:                      Record connections-env chart version
  local_action:
    module:                  shell
    cmd:                     echo "connections-env chart = {{ connections_env_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade connections-env
  command:                   "helm upgrade connections-env {{ __helm_repository_local_name }}/connections-env -i --version {{ connections_env_chart_version.stdout }} -f {{ __connections_env_install_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Check if connections-env configmap is created
  shell:                     kubectl get configmap -n {{ __default_namespace }} | grep -i connections-env
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
