---
__nobody:                                        "{{ nfs_nobody | default('nobody') }}"
__nogroup:                                       "{{ nfs_nogroup | default('nobody') }}"
__nfs_exports_destination:                       "/etc/exports"
__nfs_client_network_address:                    "{{ nfs_client_Address | default( hostvars[inventory_hostname]['ansible_default_ipv4']['network'] ) }}"
__nfs_export_netmask:                            "{{ nfs_export_netmask | default( hostvars[groups['nfs_servers'][0]]['ansible_default_ipv4']['netmask'] ) }}"
__persistentVolumePath:                          "{{ persistentVolumePath | default('pv-connections') }}"

# APISIX specific replica counts
__apisix_etcd_replicaset:                        "{{ apisix_etcd_replicaset | default('3') }}"
__apisix_namespace:                              "{{ apisix_namespace | default('connections') }}"
__apisix_etcd_pv_name:                           "{{ apisix_etcd_pv_name | default(__apisix_namespace ~ '-apisix-etcd') }}"
