---
- name: Create CNX data local mount points
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ __cnx_data_local_path }}'

- name: Mount "{{ __cnx_data_nfs_dest }}" to "{{ __cnx_data_local_path }}"
  mount:
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    src: '{{ __cnx_data_nfs_dest }}'
    path: '{{ __cnx_data_local_path }}'
