---
__setup_environment:                       "{{ setup_environment | default(true) }}"
__download_location:                       "{{ cnx_docs_download_location | default('http://c7lb1.cnx.cwp.pnp-hcl.com:8001/Docs') }}"
__package_name:                            "{{ cnx_docs_package_name | default('IBMConnectionsDocs_2.0.1.zip') }}"
__hcl_program_folder:                      "{{ hcl_program_folder | default('/opt/HCL') }}"
__extraction_folder:                       "{{ __hcl_program_folder }}/InstallBinaries/Docs"
__installation_folder:                     "{{ __extraction_folder }}"
__conversion_install_folder:               "{{ conversion_install_folder | default('DocsConversion') }}"
__editor_install_folder:                   "{{ editor_install_folder | default('DocsEditor') }}"
__viewer_install_folder:                   "{{ viewer_install_folder | default('DocsViewer') }}"
__proxy_install_folder:                    "{{ proxy_install_folder | default('DocsProxy') }}"
__docs_conversion_install_location:        "{{ __hcl_program_folder }}/{{ __conversion_install_folder }}"
__docs_editor_install_location:            "{{ __hcl_program_folder }}/{{ __editor_install_folder }}"
__docs_viewer_install_location:            "{{ __hcl_program_folder }}/{{ __viewer_install_folder }}"
__docs_editor_ext_install_location:        "{{ __hcl_program_folder }}/{{ __editor_install_folder }}/extension"
__docs_viewer_ext_install_location:        "{{ __hcl_program_folder }}/{{ __viewer_install_folder }}/extension"
__install_success_message:                 "Installation Completed Successfully"
__install_success_message_node:            "Deployment on node completed successfully"
#
__was_install_location:              "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__dmgr_profile_name:                 "{{ profile_name | default('Dmgr01') }}"
__profile_name:                      "{{ was_profile_name | default('AppSrv01') }}"
__was_cellname:                      "{{ was_cellname | default('ConnectionsCell') }}"

__db2_installation_folder:           "{{ db2_installation_folder | default('/opt/IBM/db2/V11.1') }}"
__db_concord_username:               "{{ db_concord_username | default('DOCSUSER') }}"
#
__cnx_data_path_on_cnx_server:       "{{ cnx_data_path_on_cnx_server | default('/opt/IBM/SharedArea') }}"
__cnx_data_local_path:               "{{ cnx_data_local_path | default('/mnt/cnx_data') }}"
#
__cnx_app_cluster:                   "{{ connections_auto_start_clusters | default('App') }}"
__docs_shared_storage_type_value:    "{{ docs_shared_storage_type | default('nfs') }}"
__viewer_shared_storage_type_value:  "{{ viewer_shared_storage_type | default('nfs') }}"
__cnx_shared_storage_type:           "{{ cnx_shared_storage_type | default('nfs') }}"
__viewer_data_local_path:            "{{ viewer_data_local_path | default('/mnt/viewer_data') }}"
__viewer_data_remote_path:           "{{ viewer_data_remote_path | default('/nfs/viewer_data') }}"
__docs_data_local_path:              "{{ docs_data_local_path | default('/mnt/docs_data') }}"
__docs_data_remote_path:             "{{ docs_data_remote_path | default('/nfs/docs_data') }}"

# Docs Conversion install config
__conversion_cfg_prop_location:           "{{ __extraction_folder }}/{{ __conversion_install_folder }}/installer"
__conversion_install_root:                "conversion_install_root="
__conversion_install_root_r:              "conversion_install_root={{ __docs_conversion_install_location }}"
__docs_shared_storage_type_cfg:           "docs_shared_storage_type="
__docs_shared_storage_type_r:             "docs_shared_storage_type={{ __docs_shared_storage_type_value }}"
__viewer_shared_storage_type_cfg:         "viewer_shared_storage_type="
__viewer_shared_storage_type_r:           "viewer_shared_storage_type={{ __viewer_shared_storage_type_value }}"
__docs_shared_storage_local_path:         "docs_shared_storage_local_path="
__docs_shared_storage_local_path_r:       "docs_shared_storage_local_path={{ __docs_data_local_path }}"
__docs_shared_storage_remote_server:      "docs_shared_storage_remote_server="
__docs_shared_storage_remote_server_r:    "docs_shared_storage_remote_server={{ nfsMasterAddress }}"
__docs_shared_storage_remote_path:        "docs_shared_storage_remote_path="
__docs_shared_storage_remote_path_r:      "docs_shared_storage_remote_path={{ __docs_data_remote_path }}"
__viewer_shared_storage_local_path:       "viewer_shared_storage_local_path="
__viewer_shared_storage_local_path_r:     "viewer_shared_storage_local_path={{  __viewer_data_local_path }}"
__viewer_shared_storage_remote_server:    "viewer_shared_storage_remote_server="
__viewer_shared_storage_remote_server_r:  "viewer_shared_storage_remote_server={{ nfsMasterAddress }}"
__viewer_shared_storage_remote_path:      "viewer_shared_storage_remote_path="
__viewer_shared_storage_remote_path_r:    "viewer_shared_storage_remote_path={{ __viewer_data_remote_path }}"
__was_install_root:                       "was_install_root="
__was_install_root_r:                     "was_install_root={{ __was_install_location }}/profiles/{{ __profile_name }}"
__scope:                                  "scope="
__scope_r:                                "scope=Cluster"
__scope_name:                             "scope_name="
__scope_name_r:                           "scope_name={{ __conversion_cluster_name }}"
__non_job_mgr_mode:                       "non_job_mgr_mode="
__non_job_mgr_mode_r:                     "non_job_mgr_mode=True"
__viewer_url:                             "viewer_url="
__viewer_url_r:                           "viewer_url=https://{{ docs_url }}/viewer"


# Docs Editor install config
__editor_cfg_prop_location:               "{{ __extraction_folder }}/{{ __editor_install_folder }}/installer"
__editor_install_root:                    "docs_install_root="
__editor_install_root_r:                  "docs_install_root={{ __docs_editor_install_location }}"
__shared_data_dir:                        "shared_data_dir="
__shared_data_dir_r:                      "shared_data_dir={{ __docs_data_local_path }}"
__editor_scope_name_r:                    "scope_name={{ __editor_cluster_name }}"
__db_hostname:                            "db_hostname="
__db_hostname_r:                          "db_hostname={{ groups['db2_servers'][0] }}"
__db_jdbc_driver_path:                    "db_jdbc_driver_path="
__db_jdbc_driver_path_r:                  "db_jdbc_driver_path={{ __db2_installation_folder }}/java"
__conversion_url:                         "conversion_url="
__conversion_url_r:                       "conversion_url=https://{{ docs_url }}/conversion"
__integrate_with_lc:                      "integrate_with_LC="
__integrate_with_lc_r:                    "integrate_with_LC=true"
__lc_config_xml_path:                     "LC_config_xml_path="
__lc_config_xml_path_r:                   "LC_config_xml_path={{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/LotusConnections-config.xml"
__files_url:                              "files_url=http://connections.yourdomain.com/files"
__files_url_r:                            "files_url=https://{{ cnx_application_ingress }}/files"


# Docs Viewer install config
__viewer_cfg_prop_location:               "{{ __extraction_folder }}/{{ __viewer_install_folder }}/installer"
__viewer_install_root:                    "viewer_install_root="
__viewer_install_root_r:                  "viewer_install_root={{ __docs_viewer_install_location }}"
__viewer_shared_data_dir:                 "shared_data_dir=/opt/IBM/viewer_data"
__viewer_shared_data_dir_r:               "shared_data_dir={{ __viewer_data_local_path }}"
__docs_shared_data_dir:                   "docs_shared_data_dir="
__docs_shared_data_dir_r:                 "docs_shared_data_dir={{ __docs_data_local_path }}"
__files_path:                             "files_path="
__files_path_r:                           "files_path={{ __cnx_data_local_path }}/files/upload"
__editor_installed:                       "editor_installed="
__editor_installed_r:                     "editor_installed=Yes"
__viewer_scope_name_r:                    "scope_name={{ __viewer_cluster_name }}"
__docs_url:                               "docs_url="
__docs_url_r:                             "docs_url=https://{{ docs_url }}/docs"
__ecm_fncmis_server_url:                  "ecm_fncmis_server_url="
__ecm_fncs_server_url:                    "ecm_fncs_server_url="
__ecm_community_server_url:               "ecm_community_server_url="


# Docs Editor Proxy install config
__editor_proxy_cfg_prop_location:         "{{ __extraction_folder }}/{{ __proxy_install_folder }}/installer"
__was_proxy_profile_root:                 "was_proxy_profile_root="
__was_proxy_profile_root_r:               "was_proxy_profile_root={{ __was_install_location }}/profiles/{{ __profile_name }}"
__proxy_scope_name:                       "proxy_scope_name="
__proxy_scope_name_r:                     "proxy_scope_name={{ __docs_proxy_cluster_name }}"
__docs_scope_name:                        "docs_scope_name="
__docs_scope_name_r:                      "docs_scope_name={{ __editor_cluster_name }}"


# Docs Editor Extension install config
__editor_ext_cfg_prop_location:            "{{ __extraction_folder }}/DocsCnxExtension/installer"
__ext_install_root:                        "ext_install_root="
__editor_ext_install_root_r:               "ext_install_root={{ __docs_editor_ext_install_location }}"
__files_scope_name:                        "files_scope_name="
__files_scope_name_r:                      "files_scope_name={{ cnx_files_cluster }}"
__news_scope_name:                         "news_scope_name="
__news_scope_name_r:                       "news_scope_name={{ cnx_news_cluster }}"
__common_scope_name:                       "common_scope_name="
__common_scope_name_r:                     "common_scope_name={{ cnx_common_cluster }}"
__ic_extension_path:                       "ic_extension_path="
__ic_extension_path_r:                     "ic_extension_path={{ __cnx_data_path_on_cnx_server }}/provision/webresources"
__deamon_shared_path:                      "deamon_shared_path="
__deamon_shared_path_r:                    "deamon_shared_path={{ __cnx_data_path_on_cnx_server }}"
__docs_server_url:                         "docs_server_url="
__docs_server_url_r:                       "docs_server_url=https://{{ docs_url }}/docs"
__ic_version:                              "ic_version ="
__ic_version_r:                            "ic_version=5.5"
__docs_admin_j2c_alias:                    "docs_admin_j2c_alias="
__docs_admin_j2c_alias_r:                  "docs_admin_j2c_alias=connectionsAdmin"
# not in doc
__ccm_enabled:                             "ccm_enabled="
__ccm_enabled_r:                           "ccm_enabled=False"

# Docs Viewer Extension install config:
__viewer_ext_cfg_prop_location:            "{{ __extraction_folder }}/ViewerCnxExtension/installer"
__viewer_ext_install_root_r:               "ext_install_root={{ __docs_viewer_ext_install_location }}"
__enable_upload_conversion:                "enable_upload_conversion="
__enable_upload_conversion_r:              "enable_upload_conversion=Yes"
__auth_type:                               "auth_type="
__auth_type_r:                             "auth_type=BASIC"
__viewer_server_url:                       "viewer_server_url="
__viewer_server_url_r:                     "viewer_server_url=https://{{ docs_url }}/viewer"
__viewer_admin_j2c_alias:                  "viewer_admin_j2c_alias="
__viewer_admin_j2c_alias_r:                "viewer_admin_j2c_alias=connectionsAdmin"


__conversion_install_success_file:        "{{ __docs_conversion_install_location }}/docs.conversion.installed.success"
__editor_install_success_file:            "{{ __docs_editor_install_location }}/docs.editor.installed.success"
__viewer_install_success_file:            "{{ __docs_viewer_install_location }}/docs.viewer.installed.success"
__editor_proxy_install_success_file:      "{{ __docs_editor_install_location }}/docs.editor.proxy.installed.success"
__docs_editor_ext_install_success_file:   "{{ __docs_editor_ext_install_location }}/docs.editor.ext.installed.success"
__docs_viewer_ext_install_success_file:   "{{ __docs_viewer_ext_install_location }}/docs.viewer.ext.installed.success"
