---
__setup_environment:                       "{{ setup_environment | default(true) }}"
__download_location:                       "{{ cnx_docs_download_location | default('http://c7lb1.cnx.cwp.pnp-hcl.com:8001/Docs') }}"
__package_name:                            "{{ cnx_docs_package_name | default('IBMConnectionsDocs_2.0.1.zip') }}"
__hcl_program_folder:                      "{{ hcl_program_folder | default('/opt/HCL') }}"
__extraction_folder:                       "{{ __hcl_program_folder }}/InstallBinaries/Docs"
__installation_folder:                     "{{ __extraction_folder }}"
__conversion_install_folder:               "{{ conversion_install_folder | default('DocsConversion') }}"
__editor_install_folder:                   "{{ editor_install_folder | default('DocsEditor') }}"
__viewer_install_folder:                   "{{ viewer_install_folder | default('DocsViewer') }}"
__proxy_install_folder:                    "{{ proxy_install_folder | default('DocsProxy') }}"
__docs_conversion_install_location:        "{{ __hcl_program_folder }}/{{ __conversion_install_folder }}"
__docs_editor_install_location:            "{{ __hcl_program_folder }}/{{ __editor_install_folder }}"
__docs_viewer_install_location:            "{{ __hcl_program_folder }}/{{ __viewer_install_folder }}"
__docs_editor_ext_install_location:        "{{ __hcl_program_folder }}/{{ __editor_install_folder }}/extension"
__docs_viewer_ext_install_location:        "{{ __hcl_program_folder }}/{{ __viewer_install_folder }}/extension"
__install_success_message:                 "Installation Completed Successfully"
__install_success_message_node:            "Deployment on node completed successfully"
__uninstall_success_message:               "Uninstall successfully"
#
__was_install_location:              "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__dmgr_profile_name:                 "{{ profile_name | default('Dmgr01') }}"
__profile_name:                      "{{ was_profile_name | default('AppSrv01') }}"
__was_cellname:                      "{{ was_cellname | default('ConnectionsCell') }}"
#
__cnx_deploy_type:                   "{{ cnx_deploy_type | default('small') }}"

__install_latest_db2:                "{{ install_latest_db2 | default(false) }}"
__db2_default_install_path:          "{{ '/opt/IBM/db2/V11.5' if __install_latest_db2 else '/opt/IBM/db2/V11.1' }}"
__db2_installation_folder:           "{{ db2_installation_folder | default(__db2_default_install_path) }}"
__db_concord_username:               "{{ db_concord_username | default('DOCSUSER') }}"
#
__firstNfsNode:                      "{{ '' if (groups['nfs_servers'] is not defined) else (hostvars[groups['nfs_servers'][0]]['ansible_default_ipv4']['address']) }}"
__nfsMasterAddress:                  "{{ nfsMasterAddress | default( __firstNfsNode ) }}"
#
__cnx_data_path_on_cnx_server:       "{{ cnx_data_path_on_cnx_server | default('/opt/IBM/SharedArea') }}"
__cnx_data_local_path:               "{{ cnx_data_local_path | default('/mnt/cnx_data') }}"
#
__cnx_app_cluster:                   "{{ connections_auto_start_clusters | default('App') }}"
__docs_shared_storage_type_value:    "{{ docs_shared_storage_type | default('nfs') }}"
__viewer_shared_storage_type_value:  "{{ viewer_shared_storage_type | default('nfs') }}"
__cnx_shared_storage_type:           "{{ cnx_shared_storage_type | default('nfs') }}"
__viewer_data_local_path:            "{{ viewer_data_local_path | default('/mnt/viewer_data') }}"
__viewer_data_remote_path:           "{{ viewer_data_remote_path | default('/nfs/viewer_data') }}"
__docs_data_local_path:              "{{ docs_data_local_path | default('/mnt/docs_data') }}"
__docs_data_remote_path:             "{{ docs_data_remote_path | default('/nfs/docs_data') }}"

# Docs Conversion install config
__conversion_cfg_prop_location:           "{{ __extraction_folder }}/{{ __conversion_install_folder }}/installer"
__conversion_install_root_r:              "{{ __docs_conversion_install_location }}"
__docs_shared_storage_type_r:             "{{ __docs_shared_storage_type_value }}"
__viewer_shared_storage_type_r:           "{{ __viewer_shared_storage_type_value }}"
__docs_shared_storage_local_path_r:       "{{ __docs_data_local_path }}"
__docs_shared_storage_remote_server_r:    "{{ __nfsMasterAddress }}"
__docs_shared_storage_remote_path_r:      "{{ __docs_data_remote_path }}"
__viewer_shared_storage_local_path_r:     "{{  __viewer_data_local_path }}"
__viewer_shared_storage_remote_server_r:  "{{ __nfsMasterAddress }}"
__viewer_shared_storage_remote_path_r:    "{{ __viewer_data_remote_path }}"
__was_install_root_r:                     "{{ __was_install_location }}/profiles/{{ __profile_name }}"
__scope_r:                                "Cluster"
__scope_name_r:                           "{{ __conversion_cluster_name }}"
__non_job_mgr_mode_r:                     "True"
__viewer_url_r:                           "https://{{ docs_url }}/viewer"


# Docs Editor install config
__editor_cfg_prop_location:               "{{ __extraction_folder }}/{{ __editor_install_folder }}/installer"
__editor_install_root_r:                  "{{ __docs_editor_install_location }}"
__shared_data_dir_r:                      "{{ __docs_data_local_path }}"
__editor_scope_name_r:                    "{{ __editor_cluster_name }}"

__db_hostname_default:                    "{{ db_hostname | default( hostvars[groups['db_servers'][0]]['inventory_hostname'] ) }}"
__db_hostname_r:                          "{{ __db_hostname_default }}"
#__db_type is set by get_db_type.yml
__db_type_prop_value:                     "{{ __db_type }}"
__db_name:                                "{{ db_name | default('CONCORD') }}"
__db_name_prop_value:                     "{{ __db_name }}"
__db_port_default:                        "{{ db_port | default('50000') }}"
__db_port_r:                              "{{ __db_port_default }}"

__db2_default_docs_jdbc_file:             "{{ '/opt/IBM/db2/V11.5/java' if __install_latest_db2 else '/opt/IBM/db2/V11.1/java' }}"
__db_docs_jdbc_file:                      "{{ db_docs_jdbc_file | default( __db2_default_docs_jdbc_file ) }}"
__db_jdbc_driver_path_r:                  "{{ __db_docs_jdbc_file }}"
__conversion_url_r:                       "https://{{ docs_url }}/conversion"
__integrate_with_lc_r:                    "true"
__lc_config_xml_path_r:                   "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/LotusConnections-config.xml"
__files_url_r:                            "https://{{ cnx_application_ingress }}/files"
__email_url_r:                            "https://{{ cnx_application_ingress }}/connections"


# Docs Viewer install config
__viewer_cfg_prop_location:               "{{ __extraction_folder }}/{{ __viewer_install_folder }}/installer"
__viewer_install_root_r:                  "{{ __docs_viewer_install_location }}"
__viewer_shared_data_dir_r:               "{{ __viewer_data_local_path }}"
__docs_shared_data_dir_r:                 "{{ __docs_data_local_path }}"
__files_path_r:                           "{{ __cnx_data_local_path }}/files/upload"
__editor_installed_r:                     "Yes"
__viewer_scope_name_r:                    "{{ __viewer_cluster_name }}"
__docs_url_r:                             "https://{{ docs_url }}/docs"
__ecm_fncmis_server_url:                  ""
__ecm_fncs_server_url:                    ""
__ecm_community_server_url:               ""


# Docs Editor Proxy install config
__editor_proxy_cfg_prop_location:         "{{ __extraction_folder }}/{{ __proxy_install_folder }}/installer"
__was_proxy_profile_root_r:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
__proxy_scope_name_r:                     "{{ __docs_proxy_cluster_name }}"
__docs_scope_name_r:                      "{{ __editor_cluster_name }}"


# Docs Editor Extension install config
__editor_ext_cfg_prop_location:            "{{ __extraction_folder }}/DocsCnxExtension/installer"
__editor_ext_install_root_r:               "{{ __docs_editor_ext_install_location }}"
__files_scope_name_r:                      "{{ __cnx_files_cluster }}"
__news_scope_name_r:                       "{{ __cnx_news_cluster }}"
__common_scope_name_r:                     "{{ __cnx_common_cluster }}"
__ic_extension_path_r:                     "{{ __cnx_data_path_on_cnx_server }}/provision/webresources"
__deamon_shared_path_r:                    "{{ __cnx_data_path_on_cnx_server }}"
__docs_server_url_r:                       "https://{{ docs_url }}/docs"
__ic_version_r:                            "5.5"
__docs_admin_j2c_alias_r:                  "connectionsAdmin"
# not in doc
__ccm_enabled_r:                           "False"


# Docs Viewer Extension install config:
__viewer_ext_cfg_prop_location:            "{{ __extraction_folder }}/ViewerCnxExtension/installer"
__viewer_ext_install_root_r:               "{{ __docs_viewer_ext_install_location }}"
__enable_upload_conversion_r:              "Yes"
__auth_type_r:                             "BASIC"
__viewer_server_url_r:                     "https://{{ docs_url }}/viewer"
__viewer_admin_j2c_alias_r:                "connectionsAdmin"


__conversion_install_success_file:        "{{ __docs_conversion_install_location }}/docs.conversion.installed.success"
__editor_install_success_file:            "{{ __docs_editor_install_location }}/docs.editor.installed.success"
__viewer_install_success_file:            "{{ __docs_viewer_install_location }}/docs.viewer.installed.success"
__editor_proxy_install_success_file:      "{{ __docs_editor_install_location }}/docs.editor.proxy.installed.success"
__docs_editor_ext_install_success_file:   "{{ __docs_editor_ext_install_location }}/docs.editor.ext.installed.success"
__docs_viewer_ext_install_success_file:   "{{ __docs_viewer_ext_install_location }}/docs.viewer.ext.installed.success"
