- name:                      Find elasticstack helm file
  find:
    paths:                   "{{ __helmbuilds_folder }}"
    patterns:                "elasticstack*.tgz"
    file_type:               file
  register:                  elasticstack_tgz

- name:                      "Render {{ __elasticstack_env }}"
  template:
    src:                     "helmvars/elasticstack.yml.j2"
    dest:                    "{{ __elasticstack_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Setup elasticstack
  command:                   "helm upgrade elasticstack {{ elasticstack_tgz.files[0].path }} -i -f {{ __elasticstack_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Check if logstash is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i logstash | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if kibana is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i kibana | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if filebeat is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i filebeat | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Finding Kibana link
  debug:
    msg:                     "You can reach your Kibana instance here: https://{{ load_balancer_dns }}:32333"
