---
- name:              Is Product already Installed?
  command:           "egrep {{ __product_id }} /var/ibm/InstallationManager/installed.xml"
  register:          version_already_installed
  ignore_errors:     true
  changed_when:      false