---
- name:                      Setup OrientMe and Action Center config
  include_tasks:             setup_orientme.yml

- name:                      Setup appregistry config
  include_tasks:             setup_appreg.yml

- name:                      Setup ElasticSearch config
  include_tasks:             setup_elasticsearch_config.yml

- name:                      Setup Teams config
  include_tasks:             setup_teams_config.yml
  when:                      __setup_teams|bool == true
