---
- name:                                     "Verify if properties were added"
  stat:
    path:                                   "{{ __success_file }}"
  register:                                 lcc_props_added

- name:                                     Add appreg hostname and protocol genericProperties to lcc.xml
  xml:
    path:                                   "{{ __lcc_full_path }}"
    xpath:                                  "{{ __lcc_version_xpath }}"
    namespaces:                             "{{ __lcc_namespaces }}"
    input_type: xml
    pretty_print: yes
    add_children:
      - "<genericProperty name=\"appreg.hostname\">{{ dmgr_hostname }}</genericProperty>"
      - "<genericProperty name=\"appreg.protocol\">https</genericProperty>"
  register:                                 add_node
  when:                                     lcc_props_added.stat.exists == false

- name:                                     print node
  debug:
    msg:                                    "{{ add_node.changed }}"

- name:                                     "Create {{ __success_file }} file"
  file:
    path:                                   "{{ __success_file }}"
    state:                                  touch
  when:                                     add_node.changed == true

# Query element text using XPath
- name:                                     Enable service extensionRegistry
  xml:
    path:                                   "{{ __lcc_full_path }}"
    xpath:                                  "{{ __lcc_sloc_service_extRegistry_xpath }}"
    content:                                attribute
    namespaces:                             "{{ __lcc_namespaces }}"
  register:                                 get_element_text

- name:                                     Print get_element_text@enabled
  debug: var=get_element_text.matches[0]['{http://www.ibm.com/service-location}serviceReference']['enabled']

- name:                                     Print get_element_text@ssl_enabled
  debug: var=get_element_text.matches[0]['{http://www.ibm.com/service-location}serviceReference']['ssl_enabled']

- name:                                     Service extensionRegistry@enabled
  block:
    - name:                                 Update extensionRegistry@enabled
      xml:
        path:                               "{{ __lcc_full_path }}"
        xpath:                              "{{ __lcc_sloc_service_extRegistry_xpath }}"
        value:                              "true"
        attribute:                          "enabled"
        namespaces:                         "{{ __lcc_namespaces }}"
      register:                             isExtReg_enabled
      when:                                 get_element_text.count == 1

    - name:                                 Update extensionRegistry@ssl_enabled
      xml:
        path:                               "{{ __lcc_full_path }}"
        xpath:                              "{{ __lcc_sloc_service_extRegistry_xpath }}"
        value:                              "true"
        attribute:                          "ssl_enabled"
        namespaces:                         "{{ __lcc_namespaces }}"
      register:                             isExtReg_ssl_enabled
      when:                                 get_element_text.count == 1

- name:                                     Print extensionRegistry@ssl_enabled
  debug:
    msg:  "{{ isExtReg_ssl_enabled.changed }}"

- name:                                     Print extensionRegistry@enabled
  debug:
    msg:                                    "{{ isExtReg_enabled.changed }}"
