---
__profile_name:              "{{ profile_name | default('Dmgr01') }}"
__was_cellname:              "{{ was_cellname | default('ConnectionsCell') }}"
__app_profile_name:          "{{ app_profile_name | default('AppSrv01') }}"
__was_install_location:      "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__bin_dir:                   "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin"

__cnx_major_version:         "{{ cnx_major_version | default('7') }}"

# LDAP defaults

__ldap_realm:                "{{ ldap_realm | default('dc=cnx,dc=pnp-hcl,dc=com') }}"
__ldap_server_default:       "{{ hostvars[groups['ldap_servers'][0]]['inventory_hostname'] }}"
__ldap_server:               "{{ ldap_server | default( __ldap_server_default ) }}"
__ldap_bind_user:            "{{ ldap_bind_user | default('cn=Admin,dc=cnx,dc=pnp-hcl,dc=com') }}"
__ldap_bind_pass:            "{{ ldap_bind_pass | default('password') }}"

# CNX front door
__cnx_application_ingress:   "{{ cnx_application_ingress }}"

__widgets_config_file:       "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/widgets-config.xml"
__cec_search_str:            "url=\"{webresourcesSvcRef}/../../xcc/templates/iWidgetXCCCommunityDefinition.xml\""
__cec_replace_str:           "url=\"https://{{ __cnx_application_ingress }}/xcc/templates/iWidgetXCCCommunityDefinition.xml\""

__sp_lib_search_str:         "url=\"{webresourcesSvcRef}/../../spo/SharepointWidget.xml\""
__sp_lib_replace_str:        "url=\"https://{{ __cnx_application_ingress }}/spo/SharepointWidget.xml\""

__lcc_full_path:             "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/LotusConnections-config.xml"

# LCC configuration namepspaces
__lcc_namespaces:
  xmlns="http://www.ibm.com/LotusConnections-config"
  xsi="http://www.w3.org/2001/XMLSchema-instance"
  sloc="http://www.ibm.com/service-location"
  tns="http://www.ibm.com/LotusConnections-config"

# Dynamic Host
__lcc_dynamic_host_xpath:       "/tns:config/tns:dynamicHosts"
__lcc_dynamic_host_href_xpath:  "{{ __lcc_dynamic_host_xpath }}/tns:host"
__lcc_dynamic_host_href:        "http://{{ cnx_application_ingress }}"
__lcc_dynamic_host_ssl_href:    "https://{{ cnx_application_ingress }}"

# forceConfidentialCommunications
__lcc_force_comm_xpath:        "/tns:config/tns:forceConfidentialCommunications"

# LanguageSelector
__cnx_enable_lang_selector:        "{{ cnx_enable_lang_selector | default('false') }}"
__lcc_languageselector_xpath:  "/tns:config/tns:languageSelector"

# full icec
__cnx_enable_full_icec:        "{{ cnx_enable_full_icec | default('false') }}"
__lcc_full_icec_xpath:         "/tns:config/tns:properties/tns:genericProperty[@name=\"icec.light\"]"

# Moderation - contentreview-config.xml
__cnx_enable_moderation:     "{{ cnx_enable_moderation | default('false') }}"
__contentreview_full_path:   "/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/config/cells/{{ __was_cellname }}/LotusConnections-config/contentreview-config.xml"

# Invite - selfregistration-config.xml
__selfreg_full_path:                "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/selfregistration-config.xml"
__selfreg_prereg_xpath:             "/config/pre-register"
__selfreg_reg_url_xpath:            "/config/pre-register/registration-base-url"
__selfreg_invite_usertype_xpath:    "/config/pre-register/invite-user-type"
__selfreg_hide_login_field_xpath:   "/config/pre-register/hide-field-login"
__selfreg_displayname_field_xpath:  "/config/pre-register/enable-field-displayName"
__selfreg_ldap_server_xpath:        "/config/ldap-connector/external-user-server/server"
__selfreg_ldap_auth_user_xpath:     "/config/ldap-connector/external-user-server/authentication/user"
__selfreg_ldap_auth_pwd_xpath:      "/config/ldap-connector/external-user-server/authentication/password"
__selfreg_ldap_parent_dn_xpath:     "/config/ldap-connector/external-user-server/entry/parent-dn"
__selfreg_ldap_guid_xpath:          "/config/ldap-connector/external-user-server/guid-string"
__selfreg_profile_base_guid_xpath:  "/config/profiles-connector/entry/attributes/attribute[key='com.ibm.snx_profiles.base.guid']/value"
__cnx_enable_invite:                "{{ cnx_enable_invite | default('false') }}"

# Sharepoint Widget Configuration
__sharepoint_client_id:              "{{ sharepoint_client_id | default('c14ed562-5a27-4723-82b6-62cca82d2fcc') }}"
__sharepoint_tenant_id:              "{{ sharepoint_tenant_id | default('b799d683-9a83-4044-a827-c88e16238a7b') }}"

# Files - files-config.xml
__filescfg_full_path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/files-config.xml"
__filescfg_namespaces:
 xmlns="http://www.ibm.com/connections/files/files-config/1.0"
 tns="http://www.ibm.com/connections/files/files-config/1.0"
 xsi="http://www.w3.org/2001/XMLSchema-instance"
__filescfg_filesync_xpath:          "/tns:config/tns:fileSync"

# Mobile - mobile-config.xml
__mobile_config_file:               "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/mobile-config.xml"
__mobilecfg_namespaces:
  xmlns="http://www.ibm.com/mobile-config"
  tns="http://www.ibm.com/mobile-config"
  xsi="http://www.w3.org/2001/XMLSchema-instance"
__mobilecfg_push_xpath:             "/tns:config/tns:Push"
__mobilecfg_mobileadmin_xpath:      "/tns:config/tns:MobileAdmin"

# Touchpoint - touchpoint-config.xml
__touchpoint_config_file:                         "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}/LotusConnections-config/touchpoint-config.xml"
__touchpoint_acceptinvalidsslcerts_search_str:    "<!-- acceptInvalidSSLCerts>true</acceptInvalidSSLCerts -->"
__touchpoint_acceptinvalidsslcerts_replace_str:   "<acceptInvalidSSLCerts>true</acceptInvalidSSLCerts>"
__touchpoint_acceptinvalidsslcerts:               "{{ touchpoint_acceptinvalidsslcerts | default('false') }}"
