---
- name: Enable/Disable Moderation ( {{ __cnx_enable_moderation }} )
  xml:
    path: '{{ __contentreview_full_path }}'
    xpath: '{{ item }}'
    attribute: enabled
    value: '{{ __cnx_enable_moderation |lower }}'
  with_items:
    - /config/commModerationConfiguration/preModeration/enabledByCreation
    - /config/serviceConfiguration/service[@id="blogs"]/contentApproval
    - /config/serviceConfiguration/service[@id="blogs"]/contentApproval/ownerModerate
    - /config/serviceConfiguration/service[@id="blogs"]/contentFlagging
    - /config/serviceConfiguration/service[@id="blogs"]/contentFlagging/issueCategorization
    - /config/serviceConfiguration/service[@id="files"]/contentApproval
    - /config/serviceConfiguration/service[@id="files"]/contentApproval/ownerModerate
    - /config/serviceConfiguration/service[@id="files"]/contentFlagging
    - /config/serviceConfiguration/service[@id="files"]/contentFlagging/ownerModerate
    - /config/serviceConfiguration/service[@id="forums"]/contentApproval
    - /config/serviceConfiguration/service[@id="forums"]/contentApproval/ownerModerate
    - /config/serviceConfiguration/service[@id="forums"]/contentFlagging
    - /config/serviceConfiguration/service[@id="forums"]/contentFlagging/ownerModerate
    - /config/serviceConfiguration/service[@id="forums"]/contentFlagging/issueCategorization
  when:
    - cnx_enable_moderation is defined
