---
- hosts:                    db2_servers, was_servers
  become:                   true
  roles:
    - roles/third_party/ibm/db2-install

- hosts:                    db2_servers
  become:                   true
  roles:
    - roles/hcl/connections-wizards

- hosts:                    ldap_servers
  become:                   true
  roles:
    - roles/third_party/ldap-install

- hosts:                    db2_servers
  become:                   true
  roles:
    - roles/third_party/ibm/tdi-install

- name:                    Install WebSphere Application Server - Network Deployment
  hosts:                   dmgr,was_servers
  become:                  true
  roles:
    - roles/third_party/ibm/installation-manager-install
    - roles/third_party/ibm/wasnd/was-nd-install
    - roles/third_party/ibm/wasnd/was-nd-fix-install
    - roles/third_party/ibm/wasnd/was-java-install

- name:                    Install HTTP Servers
  hosts:                   ihs_servers
  become:                  true
  roles:
    - roles/third_party/ibm/installation-manager-install
    - roles/third_party/ibm/ihs/ibm-http-server-install
    - roles/third_party/ibm/ihs/ibm-http-server-fix-install

- name:                    Setup DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-create-profile
    - roles/third_party/ibm/wasnd/was-dmgr-start
    - roles/third_party/ibm/wasnd/was-dmgr-enable-app-sec
    - roles/third_party/ibm/wasnd/was-dmgr-import-tls-cert
    - roles/third_party/ibm/wasnd/was-dmgr-config-ldap
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Setup WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-profile-create
    - roles/third_party/ibm/wasnd/was-nodeagent-start
    - roles/third_party/ibm/db2-install

- name:                    Setup HTTP Servers on DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-config-webserver
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Configure HTTP Servers
  hosts:                   ihs_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/ihs/ibm-http-config-plgwct
    - roles/third_party/ibm/ihs/ibm-http-adminctl-restart
    - roles/third_party/ibm/ihs/ibm-http-httpdconf
    - roles/third_party/ibm/ihs/ibm-http-server-restart

- name:                    Gather facts
  hosts:                   nfs_servers
  tasks:                   []

- name:                    Setup NFS
  hosts:                   dmgr, was_servers
  become:                  true
  roles:
    - roles/third_party/nfs-install

- name:                    Setup Connections
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/connections

- name:                    Connections Post Install Config
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/connections/post_install_config

- name:                    Start CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-start-cluster

- name:                    Setup HTTP Servers on DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-config-webserver
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Restart DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Restart WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-nodeagent-stop
    - roles/third_party/ibm/wasnd/was-nodeagent-start

- name:                    Configure HTTP Servers
  hosts:                   ihs_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/ihs/ibm-http-config-plgwct
    - roles/third_party/ibm/ihs/ibm-http-adminctl-restart
    - roles/third_party/ibm/ihs/ibm-http-httpdconf
    - roles/third_party/ibm/ihs/ibm-http-server-restart

- name:                    Restart CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-stop-cluster
    - roles/third_party/ibm/wasnd/was-dmgr-start-cluster

- name:                    Restart DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-restart
