---
__sudo_user:                        "{{ kubectl_user | default( ansible_env['SUDO_USER'] ) | default('lcuser') }}"
__apisix_admin_password:            "{{ apisix_admin_password | default('password') }}"
__apisix_viewer_password:           "{{ apisix_viewer_password | default('v-password') }}" 

# Secret name for APISIX credentials
__apisix_secrets_name:              "{{ apisix_secrets_name | default('apisix-admin-secret') }}"
__apisix_namespace:                 "{{ apisix_namespace | default('connections') }}"  # Namespace for APISIX resources

__ingress_nginx_secret_name:        "{{ ingress_nginx_secret_name | default('ingress-nginx-tls-secret') }}"
__default_namespace:                "{{ default_namespace | default('connections') }}"
