- name:                 Show me hostvars
  debug:
    msg:                "{{ hostvars }}"

- name:                 Show me hostvars
  debug:
    msg:                "{{ groups['k8s_masters'][0].split('.', 1)[1] }}"
