---
- name: Run profile migrations for Orientme
  shell: kubectl exec -n {{ __default_namespace }} -it $(kubectl get pods -n {{ __default_namespace }}
    | grep people-migrate | awk '{print $1}') -- sh -c "npm run start migrate"
  become_user: '{{ __sudo_user }}'
